version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: userllm
      POSTGRES_PASSWORD: passllm
      POSTGRES_DB: llm_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://userllm:passllm@db:5432/llm_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db

volumes:
  db_data: